### ISSUE TITLE
[FEAT] 아키텍처 설계

### ISSUE THREAD

**Issue by dudwls901** [Wanted-Pre-Onboarding-Android-team3-2/android-wanted-SensorDashboardApp#1]
## 🌳 내용

> Github 협업 프로세스 셋팅, Base Architecture 설계, Hilt Module 셋팅, Library Dependency 셋팅

## 🍀 Progress
- [x] Project, Label, Issue template, PR template, develop branch merge rule 셋팅
- [x] Library Dependency 셋팅
- [x] Base Architecture 설계(Clean Architecture, mvvm) - package
- [x] Hilt Module 셋팅

**Comment by KimHance** [comment]
gitignore 도 등록해두면 좋을 것 같습니다.
https://www.toptal.com/developers/gitignore
